### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by Ximer612** [LeoniePhiline/showcase-dl#1] opened 2023-02-08 22:27 UTC
When i put the URL to download it gives me "FINISHED" but it dosen't have downloaded anything. I tried even with a vimeo public video

**Comment by LeoniePhiline** [comment] 2023-02-08 23:10
Do you have `yt-dlp` installed?

**Comment by LeoniePhiline** [comment] 2023-02-10 10:43
In the meantime, I was able to reproduce it. I believe yt-dlp changed their output pattern. I will adjust the app to that.

**Comment by LeoniePhiline** [comment] 2023-02-10 12:50
# Okay, so I made some changes to get this to work for you.

1. This patch works: https://github.com/yt-dlp/yt-dlp/issues/6149#issuecomment-1416087496
2. I created a PR for it: https://github.com/yt-dlp/yt-dlp/pull/6203
3. I implemented "Bring your own downloader", so you can use a custom-patched `yt-dlp` or `youtube-dl`

# Here's what you can do to get it working already before `yt-dlp` merges this upstream:

## 1. Get the `yt-dlp` code with the fix

```
git clone https://github.com/yt-dlp/yt-dlp.git
cd yt-dlp
git fetch origin pull/6203/head
git checkout FETCH_HEAD
```

## 2. Update `showcase-dl` to get my latest features

```
cd path/to/showcase-dl
git pull
```

## 3. Run `showcase-dl` with custom downloader

```
cargo run --release -- -vv --bin /your/path/to/yt-dlp/yt-dlp.sh <URL of webpage containing vimeo embeds>
```

### Optionally observe the log

#### Use more `v` for more verbosity: 

- errors are always reported
- `-v` is `warn`.
- `-vv` is `info`. 
- `-vvv` is `debug` (probably enough).
- `-vvvv` is `trace` (probably too much).

#### Follow the log

Open a new terminal or side-by-side pane. There, follow the log with:

```
tail -f vimeo-showcase.log`

**Comment by LeoniePhiline** [comment] 2023-02-10 13:55
https://github.com/yt-dlp/yt-dlp/pull/6203 was merged. You can use `yt-dlp` `master`; no more need for `FETCH_HEAD`.

**Closed** 2023-02-10 14:18 UTC

**Comment by Ximer612** [comment] 2023-02-10 14:20
> Do you have `yt-dlp` installed?

yes i have it installed

**Comment by LeoniePhiline** [comment] 2023-02-10 14:22
Follow the instructions above (read both https://github.com/LeoniePhiline/showcase-dl/issues/1#issuecomment-1425766630 and https://github.com/LeoniePhiline/showcase-dl/issues/1#issuecomment-1425843692) and let me know if that fixes it.

**Comment by Ximer612** [comment] 2023-02-10 18:09
What should do "tail -f vimeo-showcase.log`"?

**Comment by Ximer612** [comment] 2023-02-10 18:10
And how to use cookies to download video?

**Comment by LeoniePhiline** [comment] 2023-02-10 18:52
`tail -f vimeo-showcase.log` helps you see what is going on. It shows you the log output of the application live. Should work on Linux and Mac. No idea how to watch files on Windows... Are you on Windows?

> And how to use cookies to download video?

Not currently supported, as I don't have a use case. If you provide me with some URL and cookies, I can try implementing that for you, though. (Not right now. Maybe on Sunday?)

**Comment by tylerhunt** [comment] 2023-02-12 13:05
I'm still having this issue when running with both the latest `showcase-dl` and `yt-dlp` and using the `--bin` option. No errors being reported in the log, but nothing downloads. I've tried with both the source page and the embed URL itself.

**Comment by LeoniePhiline** [comment] 2023-02-12 13:56
Did you try with `-vvv` for more log output? What do the logs say in that case? (Ideally share the log via a service like https://paste.opensuse.org/)

Truncate or delete the log before you start the app, to get a clean single-run log. 

> nothing downloads 

what does the app act like and how does it look? Does it display the videos as „finished“ from the start? (Maybe a screenshot will help)

**Comment by tylerhunt** [comment] 2023-02-13 13:25
Here's the log: <https://paste.opensuse.org/pastes/cf93025f53e0>

And here's what the app looks like:
<img width="563" alt="Screen Shot 2023-02-13 at 08 20 40" src="https://user-images.githubusercontent.com/6457/218469702-258c6e95-59d8-4be9-ab28-391a102aa682.png">

**Comment by LeoniePhiline** [comment] 2023-02-13 15:58
I assume you're going for this single video: https://player.vimeo.com/video/796389232?h=660764310a rather than the huge showcase at https://vimeo.com/showcase/9030944/embed ?

That's just a normal vimeo video. You need no special app beyond `yt-dlp` for that.

The latest `yt-dlp` release does not work with vimeo, but on the current `master` branch it is fixed. 

This should work (on Linux and Mac):

1. Clone yt-dlp to get the vimeo fix:
```
git clone https://github.com/yt-dlp/yt-dlp.git
```

2. Use it:
```
./yt-dlp/yt-dlp.sh https://player.vimeo.com/video/796389232\?h\=660764310a
```

Note that the `?` and `=` are escaped with an `\` each. 

Alternatively, use quotes:
```
./yt-dlp/yt-dlp.sh "https://player.vimeo.com/video/796389232?h=660764310a"
```

**Comment by tylerhunt** [comment] 2023-02-13 16:32
Ah, that did work. Thank you.
